### PR TITLE
Add hevm and jshon to the nix shell

### PR DESCRIPTION
**Pull request by brianmcmichael**
Contract verification dependencies.

### CODE REVIEW

**Comment by gbalabasquer** [comment]
Hey, two comments about it:
1 - could we switch `jshon` to `jq` as we are already using it in the project?
2 - respecting `hevm` I'd like some comments from @icetan as I'm not really sure how we should add new modules. I guess `hevm` should be defined in the same place where we have `seth` and `dapp`.

**Comment by icetan** [comment]
> 1 - could we switch `jshon` to `jq` as we are already using it in the project?

Is `jshon` used by some script? If so it should be added as a dependency for that script and if possible we should probably use `jq` instead.

Or are you using `jshon` in some other way, like for experimenting?

> 2 - respecting `hevm` I'd like some comments from @icetan as I'm not really sure how we should add new modules. I guess `hevm` should be defined in the same place where we have `seth` and `dapp`.

If we want to use `hevm` for experimenting with smart contracts this might be a good place to put it. You can see the dependencies for the `nix-shell` as the tools you want to be able to have handy for doing work in the project.

**Comment by gbalabasquer** [comment]
@brianmcmichael is working on a new script in this repo which will verify the contracts in Etherscan.
The `jq` question is more for him, to see if he can use it instead of `jshon` as we are already using it in the main script.

Regarding `hevm` I think is for getting the flatten solidity files for this same Etherscan script. What I'm wondering is this inclusion needs to be done in this `shell.nix` file or should come from somewhere else. `dapp` and `seth` are being used by the scripts but are not in that nix file, so they are coming from another source.

**Comment by brianmcmichael** [comment]
`jq` is already included in the packaging, but `jshon` is also used in [dapptools](https://github.com/dapphub/dapptools/blob/master/src/dapp/libexec/dapp/dapp-verify-contract#L35), so we need it to run the existing code. We need to have both available in the nix shell for now.

**Comment by brianmcmichael** [comment]
So yes, ideally these would get pulled in at a higher level.

**Comment by gbalabasquer** [comment]
@brianmcmichael could you please confirm this PR can be closed as the verification script will be in another repo?

**Comment by brianmcmichael** [comment]
Yes, verification will happen in it's own place. And I think that although dapptools also uses these applications they are scoped to their nix package, so we should be alright.

**Pull request closed without merging**
