### PR TITLE
Ignore submodules

### PR DESCRIPTION
**Pull request by brianmcmichael**
When a submodule and dapp.nix is updated git prompts us to commit the modifications. 

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   contracts/dss-deploy (new commits)
	modified:   contracts/dss-proxy-actions (new commits)
	modified:   contracts/scd-mcd-migration (new commits)
	modified:   nix/dapp.nix
```

We don't want to do that here so we can ignore submodule changes to prevent git from nagging about them.

After update:

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   nix/dapp.nix
```

### CODE REVIEW

**Comment by brianmcmichael** [comment]
Build is failing due to the pr from a fork cachix error. Same as @godsflaw noticed the other day. I may look into how we can resolve this because it will be a chronic issue.

**Comment by brianmcmichael** [comment]
Leaving this here for reference

```
...
copying path '/nix/store/l1q0w9qml3ybwqcdyq94lvcz3d7mv5y6-dss-deploy-optimized' from 'https://tdds.cachix.org'...
copying path '/nix/store/wrpw4px8mx05ngqpjvlx0hcg2ddw21qd-dss-deploy' from 'https://tdds.cachix.org'...
copying path '/nix/store/6nqyjybd0wkq7pdhxw0rp9g8xsawmb6g-dss-deploy-scripts' from 'https://tdds.cachix.org'...
cachix: FatalError {fatalErrorMessage = "You need to: export CACHIX_SIGNING_KEY=XXX"}
The command "nix-build -j2 | cachix push tdds" exited with 1.
Done. Your build exited with 1.
```

**Comment by godsflaw** [comment]
@brianmcmichael The problem is that the cachix API key is only available in CI from the context of the main repository.  If you push this branch to the upstream, CI will pass.

**Comment by brianmcmichael** [comment]
Done

**Pull request closed without merging**
