### PR TITLE
reorganize scripts under subdirectories

### PR DESCRIPTION
**Pull request by asymmetric**
Gathering early feedback before putting more effort into this.

### CODE REVIEW

**Comment by gbalabasquer** [comment]
I'm not really sure we should make more subdirectories on these cases.
Btw, are we setting back the `.sh` to all these files?

**Comment by asymmetric** [comment]
Nope, the extensions won't be readded, @icetan convinced me it didn't look good :)

Basically the idea is that only scripts run from an interactive shell get the `.sh` extension - and I'm not even sure we want it there.

About the subdirectories: my idea (poorly shown by this PR) is to take part of the name (`set-`) and recognize that it denotes a type of script, and therefore represent that with a directory (`setters`).

I thought this would make the project's organization easier to  grasp.

**Comment by gbalabasquer** [comment]
> Basically the idea is that only scripts run from an interactive shell get the `.sh` extension - and I'm not even sure we want it there.

Ok sounds good.



> About the subdirectories: my idea (poorly shown by this PR) is to take part of the name (`set-`) and recognize that it denotes a type of script, and therefore represent that with a directory (`setters`).
> 
> I thought this would make the project's organization easier to grasp.

Yeah I got the idea,  but not sure if we should this so explicit. For example `set-ilks-osm` (a new one) deploys contracts and also set them in the spotter.

**Comment by asymmetric** [comment]
OK, let's close this.

**Pull request closed without merging**
