### PR TITLE
SC-2026 TUSD Kovan deployment

### PR DESCRIPTION
**Pull request by brianmcmichael**
Adds config and ilk-deployer for TUSD

PIP and GEM have been deployed.

Needs a review and deployment from Kovan deployer address

### CODE REVIEW

**Comment by gbalabasquer** [comment]
I think the kovan contracts are fine, not really need to deploy them again. We should set the ownership of the `DSValue` to the PauseProxy (if not already done) and that's all.
I'll get the `DSValue` for mainnet soon.
Now that `dss-deploy` is merged, you can proceed upgrading the dependencies.

**Comment by gbalabasquer** [comment]
> And btw we should modify the `TUSD` contract in `dss-deploy` to be a proxy and implementation contract. In the future we should do the same with `USDC` as well.

Never mind with this idea. It gets quite complicated to do it.

**Comment by brianmcmichael** [comment]
> I think the kovan contracts are fine, not really need to deploy them again. We should set the ownership of the `DSValue` to the PauseProxy (if not already done) and that's all.
> I'll get the `DSValue` for mainnet soon.
> Now that `dss-deploy` is merged, you can proceed upgrading the dependencies.

To confirm, the DSValue owner should be updated to `0x0e4725db88Bb038bBa4C4723e91Ba183BE11eDf3` on Kovan.

Currently the USDC DSValue is also set to my address. I should update that as well, just need a sanity check on the address before I do so.

**Comment by brianmcmichael** [comment]
`PIP_SAI` was set to that address, so I've updated USDC and TUSD pips to set owner to `0x0e4725db88Bb038bBa4C4723e91Ba183BE11eDf3`

**Comment by gbalabasquer** [comment]
> `PIP_SAI` was set to that address, so I've updated USDC and TUSD pips to set owner to `0x0e4725db88Bb038bBa4C4723e91Ba183BE11eDf3`

Yes that is fine and in theory the creator should `deny` itself after. That is what will happen on mainnet.

**Comment by gbalabasquer** [comment]
Nvm, this is a `DSValue`, so just one `owner`.

**Pull request merged**
